defmodule Mc.Mappings do
  alias Mc.Modifier, as: M

  def standard do
    %{
      a: M.App,
      add: M.Add,
      app: M.App,
      append: M.Append,
      appendk: M.AppendK,
      apps: M.AppS,
      b: M.Buffer,
      buffer: M.Buffer,
      casel: M.CaseL,
      caseu: M.CaseU,
      countc: M.CountC,
      countl: M.CountL,
      countw: M.CountW,
      d: M.Delete,
      delete: M.Delete,
      div: M.Div,
      email: M.Email,
      erase: M.Erase,
      error: M.Error,
      field: M.Field,
      find: M.FindK,
      findv: M.FindV,
      g: M.Grep,
      get: M.Get,
      getm: M.GetM,
      getb: M.GetB,
      grep: M.Grep,
      grepv: M.GrepV,
      gv: M.GrepV,
      head: M.Head,
      hsel: M.Hsel,
      hselc: M.HselC,
      htab: M.Htab,
      invert: M.Invert,
      iword: M.Iword,
      join: M.Join,
      json: M.Json,
      jsona: M.JsonA,
      m: M.Map,
      map: M.Map,
      mapc: M.MapC,
      mul: M.Mul,
      prepend: M.Prepend,
      prependk: M.PrependK,
      r: M.Replace,
      range: M.Range,
      regex: M.Regex,
      replace: M.Replace,
      run: M.Run,
      runk: M.RunK,
      s: M.Script,
      script: M.Script,
      select: M.Select,
      set: M.Set,
      setm: M.SetM,
      sort: M.Sort,
      sortv: M.SortV,
      split: M.Split,
      splitr: M.SplitR,
      squeeze: M.Squeeze,
      stop: M.Stop,
      sub: M.Sub,
      tail: M.Tail,
      trim: M.Trim,
      url: M.Url,
      urlp: M.UrlP,
      version: M.Version,
      zip: M.Zip,
      *: M.Mul,
      +: M.Add,
      -: M.Sub,
      /: M.Div
    }
  end

  def s, do: standard()
end
