defmodule Mc.Mappings do
  defstruct [
    *: {Mc.Modifier.Multiply, :modify},
    +: {Mc.Modifier.Add, :modify},
    -: {Mc.Modifier.Subtract, :modify},
    /: {Mc.Modifier.Divide, :modify},
    app: {Mc.Modifier.App, :modify},
    append: {Mc.Modifier.Append, :modify},
    buffer: {Mc.Modifier.Buffer, :modify},
    ccount: {Mc.Modifier.Ccount, :modify},
    delete: {Mc.Modifier.Delete, :modify},
    email: {Mc.Modifier.Email, :modify},
    error: {Mc.Modifier.Error, :modify},
    find: {Mc.Modifier.Find, :modify},
    get: {Mc.Modifier.Get, :modify},
    getb: {Mc.Modifier.Getb, :modify},
    grep: {Mc.Modifier.Grep, :modify},
    head: {Mc.Modifier.Head, :modify},
    hsel: {Mc.Modifier.Hsel, :modify},
    htab: {Mc.Modifier.Htab, :modify},
    if: {Mc.Modifier.If, :modify},
    invert: {Mc.Modifier.Invert, :modify},
    iword: {Mc.Modifier.Iword, :modify},
    join: {Mc.Modifier.Join, :modify},
    json: {Mc.Modifier.Json, :modify},
    lcase: {Mc.Modifier.Lcase, :modify},
    lcount: {Mc.Modifier.Lcount, :modify},
    map: {Mc.Modifier.Map, :modify},
    mcast: {Mc.Modifier.Mcast, :modify},
    prepend: {Mc.Modifier.Prepend, :modify},
    range: {Mc.Modifier.Range, :modify},
    regex: {Mc.Modifier.Regex, :modify},
    replace: {Mc.Modifier.Replace, :modify},
    run: {Mc.Modifier.Run, :modify},
    set: {Mc.Modifier.Set, :modify},
    sort: {Mc.Modifier.Sort, :modify},
    split: {Mc.Modifier.Split, :modify},
    squeeze: {Mc.Modifier.Squeeze, :modify},
    tail: {Mc.Modifier.Tail, :modify},
    trim: {Mc.Modifier.Trim, :modify},
    ucase: {Mc.Modifier.Ucase, :modify},
    url: {Mc.Modifier.Url, :modify},
    urlp: {Mc.Modifier.Urlp, :modify},
    version: {Mc.Modifier.Version, :modify},
    wcount: {Mc.Modifier.Wcount, :modify},
    zip: {Mc.Modifier.Zip, :modify},

    # Aliases
    a: {Mc.Modifier.App, :modify},
    b: {Mc.Modifier.Buffer, :modify},
    d: {Mc.Modifier.Delete, :modify},
    g: {Mc.Modifier.Grep, :modify},
    m: {Mc.Modifier.Map, :modify},
    r: {Mc.Modifier.Replace, :modify}
  ]
end
