defmodule Mc.Mappings do
  def standard do
    %{
      a: Mc.Modifier.App,
      add: Mc.Modifier.Add,
      app: Mc.Modifier.App,
      append: Mc.Modifier.Append,
      appendk: Mc.Modifier.AppendK,
      apps: Mc.Modifier.AppS,
      b: Mc.Modifier.Buffer,
      buffer: Mc.Modifier.Buffer,
      casel: Mc.Modifier.CaseL,
      caseu: Mc.Modifier.CaseU,
      countc: Mc.Modifier.CountC,
      countl: Mc.Modifier.CountL,
      countw: Mc.Modifier.CountW,
      d: Mc.Modifier.Delete,
      delete: Mc.Modifier.Delete,
      div: Mc.Modifier.Div,
      email: Mc.Modifier.Email,
      erase: Mc.Modifier.Erase,
      error: Mc.Modifier.Error,
      find: Mc.Modifier.FindK,
      findv: Mc.Modifier.FindV,
      g: Mc.Modifier.Grep,
      get: Mc.Modifier.Get,
      getm: Mc.Modifier.GetM,
      getb: Mc.Modifier.GetB,
      grep: Mc.Modifier.Grep,
      grepv: Mc.Modifier.GrepV,
      gv: Mc.Modifier.GrepV,
      head: Mc.Modifier.Head,
      hsel: Mc.Modifier.Hsel,
      hselc: Mc.Modifier.HselC,
      htab: Mc.Modifier.Htab,
      invert: Mc.Modifier.Invert,
      iword: Mc.Modifier.Iword,
      join: Mc.Modifier.Join,
      json: Mc.Modifier.Json,
      jsona: Mc.Modifier.JsonA,
      m: Mc.Modifier.Map,
      map: Mc.Modifier.Map,
      mapc: Mc.Modifier.MapC,
      mul: Mc.Modifier.Mul,
      prepend: Mc.Modifier.Prepend,
      prependk: Mc.Modifier.PrependK,
      r: Mc.Modifier.Replace,
      range: Mc.Modifier.Range,
      regex: Mc.Modifier.Regex,
      replace: Mc.Modifier.Replace,
      run: Mc.Modifier.Run,
      runk: Mc.Modifier.RunK,
      set: Mc.Modifier.Set,
      setm: Mc.Modifier.SetM,
      sort: Mc.Modifier.Sort,
      sortv: Mc.Modifier.SortV,
      split: Mc.Modifier.Split,
      splitr: Mc.Modifier.SplitR,
      squeeze: Mc.Modifier.Squeeze,
      stop: Mc.Modifier.Stop,
      sub: Mc.Modifier.Sub,
      tail: Mc.Modifier.Tail,
      trim: Mc.Modifier.Trim,
      url: Mc.Modifier.Url,
      urlp: Mc.Modifier.UrlP,
      version: Mc.Modifier.Version,
      zip: Mc.Modifier.Zip,
      *: Mc.Modifier.Mul,
      +: Mc.Modifier.Add,
      -: Mc.Modifier.Sub,
      /: Mc.Modifier.Div
    }
  end

  def s, do: standard()
end
